name: 'overbase_firebase'
version: '0.1.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  overbase_firebase:
    # Applies to all files under models/example/
    materialized: table
    schema: overbase
    +persist_docs:
      relation: true
      columns: true

seeds:
  overbase_firebase:
    schema: overbase

vars: 
  overbase_firebase:
    "OVERBASE:DONT_CARE": "MAKE_YAML_WORK" # optional
    # don't define variables here, because if they aren't overwritten in the client yml, then they will resolve to "None". 
    # Instead, use them in the package where you need them with them with the appropriate default value
    # Furthermore, whatever we use in sources.yml, we can't define in this package's dbt_project.yml, or else they won't be able to be overwritten by the client
    # Any mandatory variables you want to be enforced should go into overbase_mandatory_vars.sql
    # The comments liste here is just for our sanity & easier c/p in client configs
    # "OVERBASE:FIREBASE_PROJECT_ID": "overbase" # mandatory, but used in sources.yml
    # "OVERBASE:FIREBASE_ANALYTICS_DATASET_ID": "firebase_analytics_raw_test" # mandatory, but used in sources.yml
    # "OVERBASE:FIREBASE_ANALYTICS_EVENTS_TABLE_NAME": "events_*" # optional, but used in sources.yml
    # "OVERBASE:FIREBASE_ANALYTICS_EVENTS_INTRADAY_TABLE_NAME": "events_intraday_*" # optional, but used in sources.yml
    # "OVERBASE:FIREBASE_ANALYTICS_CUSTOM_INSTALL_EVENT": "" # optional e.g. attributed_first_open
    # "OVERBASE:FIREBASE_ANALYTICS_DEFAULT_INCREMENTAL_DAYS":  # optional
    # "OVERBASE:FIREBASE_CRASHLYTICS_DEFAULT_INCREMENTAL_DAYS":  # optional
    # "OVERBASE:FIREBASE_ANALYTICS_FULL_REFRESH_START_DATE": "2018-01-01" # mandatory
    # "OVERBASE:FIREBASE_ANALYTICS_FULL_REFRESH_END_DATE": "2019-01-05" #optional, if you want to make
    # "OVERBASE:FIREBASE_CRASHLYTICS_FULL_REFRESH_START_DATE": "2018-01-01" # mandatory
    # "OVERBASE:FIREBASE_CRASHLYTICS_FULL_REFRESH_END_DATE": "20219-01-05" #optional, if you want to make
    # "OVERBASE:FIREBASE_CRASHLYTICS_ANALYTICS_EVENTS_FOR_CRASH_RATE": # optional, any custom FB Analytics events to calculate crashes against
    #     - spend_virtual_currency
    #     - start_trial
    # "OVERBASE:OB_DIMENSION_TO_EXCLUDE_IN_ROLLUPS":  # optional, what built-in OB dimensions to exclude from bubbling up in the rollups (& save the row count)
    #   - geo.city
    #   - geo.metro
    # "OVERBASE:CUSTOM_USER_PROPERTIES":  # data_types : "string", "int", "float", "double"
          # - { property_name: up_just_in_raw, data_type: 'string'} 
          # - { property_name: first_open_time, data_type: 'int'} 
          # - { property_name: poorly_set_variable, data_type: 'double'}
    # "OVERBASE:CUSTOM_EVENT_PARAMETERS":  # data_types : "string", "int", "float", "double"
          # - { property_name: quantity, data_type: 'int',  rollup_type: 'metric'}
          # - { property_name: quantity, data_type: 'int',  rollup_type: 'metric', metric_rollup_transformation: 'SUM(##)', field_name: 'quantity_int_sum2' }
          # - { property_name: quantity, data_type: 'int',  rollup_type: 'metric', metric_rollup_transformation: 'AVG(##)', field_name: 'quantity_avg' }
          # - { property_name: myDimension, data_type: 'string',  rollup_type: 'alsoForceNullDimension'}
          # - { property_name: server_sent_ts, data_type: 'string',  rollup_type: 'dimension', extract_transformation: 'TIMESTAMP(##)', output_data_type: 'TIMESTAMP', field_name: 'server_sent_ts' }
    # "OVERBASE:CUSTOM_CRASHLYTICS_KEYS":  # data_types : "string", "int", "float", "double"
          # - { property_name: network_state, data_type: 'string'}

