name: 'overbase_firebase'
version: '0.1.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  overbase_firebase:
    # Applies to all files under models/example/
    materialized: table
    schema: overbase

vars: 
  # mandatory variables. The same value needs to be put in overbase_mandatory_vars.sql
  # whatever we use in sources.yml, we can't define in this package's dbt_project.yml, or else they won't be able to be overwritten by the client
  overbase_firebase:
    "OVERBASE:DONT_CARE": "MAKE_YAML_WORK" # optional
    # "OVERBASE:FIREBASE_PROJECT_ID": "overbase" # mandatory, but used in sources.yml
    # "OVERBASE:FIREBASE_ANALYTICS_DATASET_ID": "firebase_analytics_raw_test" # mandatory, but used in sources.yml
    # "OVERBASE:FIREBASE_ANALYTICS_EVENTS_TABLE_NAME": "events_*" # optional, but used in sources.yml
    # "OVERBASE:FIREBASE_ANALYTICS_EVENTS_INTRADAY_TABLE_NAME": "events_intraday_*" # optional, but used in sources.yml
    #"OVERBASE:CUSTOM_USER_PROPERTIES":  # data_types : "string", "int", "float", "double"
    #        - { property_name: plays_progressive, data_type: 'string' } 
    #        - { property_name: first_open_time, data_type: 'int' } 
    #        - { property_name: poorly_set_variable, data_type: 'double' }
  