version: 2

sources:
  - name: firebase_analytics
    database: "{{ var( 'OVERBASE:FIREBASE_PROJECT_ID', 'overbase') }}"
    schema: "{{ var( 'OVERBASE:FIREBASE_ANALYTICS_DATASET_ID', 'firebase_analytics_raw_test')}}"
    tables:
      - name: events
        identifier: "{{ var( 'OVERBASE:FIREBASE_ANALYTICS_EVENTS_TABLE_NAME', 'events_*')}}"
      - name: events_intraday
        identifier: "{{ var( 'OVERBASE:FIREBASE_ANALYTICS_EVENTS_INTRADAY_TABLE_NAME', 'events_intraday_*')}}"

