version: 2

sources:
  - name: firebase_events
    database: "{{ var( 'OVERBASE:FIREBASE_PROJECT_ID', target.project) }}"
    schema: "{{ var( 'OVERBASE:FIREBASE_DATASET_ID', 'placeholder_dataset')}}"
    tables:
      - name: events
        identifier: "{{ var( 'OVERBASE:FIREBASE_EVENTS_TABLE_NAME', 'event_intraday_*')}}"
